# Generated by Django 4.2.2 on 2023-06-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='key',
        ),
        migrations.AddField(
            model_name='link',
            name='short_link',
            field=models.CharField(default='aaaaaa', max_length=200),
            preserve_default=False,
        ),
    ]
