# Generated by Django 4.2.2 on 2023-06-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_link_key_link_short_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='short_link',
        ),
        migrations.AddField(
            model_name='link',
            name='key',
            field=models.CharField(default='ababab', max_length=200),
        ),
    ]
