# Generated by Django 4.2.2 on 2023-06-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_link_short_link_link_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='key',
            field=models.CharField(default='ababab', max_length=200, unique=True),
        ),
    ]
